language: haskell

ghc:
  - 7.0.4
  - 7.2.2
  - 7.4.2
  - 7.6.3
  - 7.8.4
  - 7.10.3
  - 8.0.2
  - 8.2.2
  - 8.4.4
  - 8.6.5
  - 8.8.4
  - 8.10.4
  - 9.0.1

# I cannot seem to prevent the needless "cabal update"!

install:
  - ghc -O2 TestSuite.hs

script:
  # (["-+","+-"],True)
  # (["-+","+-","++"],True)
  - test "$(time ./TestSuite | cksum)" = '2217717056 43'

