language: haskell

ghc:
  - 7.2.1
  - 7.2.2
  - 7.4.1
  - 7.4.2
  - 7.6.1
  - 7.6.2
  - 7.6.3
  - 7.8.1
  - 7.8.2
  - 7.8.3
  - 7.8.4
  - 7.10.1
  - 7.10.2
  - 7.10.3
  - 8.0.1
  - 8.0.2
  - 8.2.1
  - 8.2.2
  - 8.4.1
  - 8.4.2
  - 8.4.3
  - 8.4.4
  - 8.6.1
  - 8.6.2
  - 8.6.3
  - 8.6.4
  - 8.6.5
  - 8.8.1

install:
  - ghc -O2 TestSuite.hs

script:
  # (["-+","+-"],True)
  # (["-+","+-","++"],True)
  - test "$(./TestSuite | cksum)" = '2217717056 43'

