on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      matrix:
        ghc: ['8.0', '8.10', '9.6']
        # Should work but does not.
        # include:
        #  - os: ubuntu-20.04
        #    ghc: '7.10'
    name: GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          # Can't not install Cabal, but at least skip this.
          cabal-update: false
      - run: ghc -O2 TestSuite.hs
      # (["-+","+-"],True)
      # (["-+","+-","++"],True)
      - run: test "$(time ./TestSuite | tee /dev/stderr | cksum)" = '2217717056 43'

