on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      matrix:
        ghc: ['8.0', '9.4', '9.6', '9.8', '9.10', '9.12']
        # Should work but doesn't.
        # include:
        # - os: ubuntu-20.04
        #   ghc: '7.10'
    name: GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          # Can't not install Cabal, but at least skip this.
          cabal-update: false
      - run: ghc -O2 -Wno-x-partial TestSuite.hs
      - run: test "$(echo $(time ./TestSuite | tee /dev/stderr))" = '(["-+","+-"],True) (["-+","+-","++"],True)'

